title: Ari Victor
tag_text: Ari
description: Ari Victor's personal blog

# GitHub repository for edit links
github:
  repository_nwo: arivictor/arivictor.github.io
  
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
